### ISSUE TITLE
Virtual appliance?

### ISSUE THREAD

**Issue by ScottBeeson** [eleme/bell.js#119]
Wondering if there is a preconfigured Bell.js VM anywhere I could download.  I'm having trouble getting everything set up.

**Comment by hit9** [comment]
Sorry, currently there isn't a pre-setup vm.

**Comment by hit9** [comment]
I'm working on a new approach **only for metric anomalies detection**, the new way dose not require ssdb, beanstalkd etc, but there's no metric visualization either, just only for monitoring.

**Comment by ScottBeeson** [comment]
That sounds cool, beanstalk and ssdb are what I'm having trouble with. I  already have a custom UI anyway so just the logic for catching the anomalies would be perfect!  Good luck!
